### ISSUE TITLE
i get this error when trying to install

### ISSUE THREAD

**Issue by lad52** [robb-smarrt/nl.ROBBshop.ROBB-smarrt#3]
![image](https://user-images.githubusercontent.com/40898339/57579742-bb735d00-74a0-11e9-8646-3dc2c5a9e5bf.png)

**Comment by TedTolboom** [comment]
@lad52 which Homey SW are you using?

To me it seems like Homey SW 1.5.13.

Athom introduced some changes in the app validation toward SW 2.x and as it appears relaxed the usage of an underscore in the driver ID name. 

Apparently, this is not possible on 1.5.x releases, although not documented. Since I developed the app on 2.x, this issue didn’t get detected...

Changing the driver ID now to remove the underscore, will break functionality for the users on 2.x.

I’ll check with Athom if there are other options.

**Comment by lad52** [comment]
> @lad52 which Homey SW are you using?
> 
> To me it seems like Homey SW 1.5.13.
> 
> Athom introduced some changes in the app validation toward SW 2.x and as it appears relaxed the usage of an underscore in the driver ID name.
> 
> Apparently, this is not possible on 1.5.x releases, although not documented. Since I developed the app on 2.x, this issue didn’t get detected...
> 
> Changing the driver ID now to remove the underscore, will break functionality for the users on 2.x.
> 
> I’ll check with Athom if there are other options.

Thanks
it is 1.5
I will try to download from github and modify the IDs as a temporary soulution befora I upgrade
